# Service
---
apiVersion: v1
kind: Service
metadata:
  name: homarr-service
  namespace: stage
spec:
  selector:
    app: homarr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7575
  type: LoadBalancer
  loadBalancerIP: 192.168.1.53
