apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ubuntu-argocd
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Dubovsky-Andrey/kubernetes-public
    targetRevision: HEAD
    path: apps/ubuntu

  destination:
    server: https://kubernetes.default.svc
    namespace: stage

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
