# PersistentVolume
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ubuntu-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: PLACEHOLDER
    server: PLACEHOLDER
