# Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      volumes:
        - name: postgresql-storage
          persistentVolumeClaim:
            claimName: postgresql-pvc
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-pvc
      containers:
        ports:
          - containerPort: 9090
        envFrom:
          - configMapRef:
              name: postgresql-config
        volumeMounts:
          - name: postgresql-storage
            mountPath: /var/lib/postgresql/data

        resources:
          requests:
            memory: "512Mi"
            cpu: "1000m"
          limits:
            memory: "1024Mi"
            cpu: "2000m"
