# Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      volumes:
        - name: postgresql-script
          configMap:
            name: postgresql-script
            items:
              - key: start.sh
                path: start.sh
        - name: postgresql-storage
          persistentVolumeClaim:
            claimName: postgresql-pvc
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-pvc
      containers:
        - name: postgres
          image: postgres:17.4
          env:
            - name: POSTGRES_DB
              value: test
            - name: POSTGRES_USER
              value: test
            - name: POSTGRES_PASSWORD
              value: test
          command:
            - /bin/bash
          ports:
            - containerPort: 9090
          envFrom:
            - configMapRef:
                name: postgresql-config
          volumeMounts:
            - name: postgresql-storage
              mountPath: /var/lib/postgresql/data

          resources:
            requests:
              memory: "512Mi"
              cpu: "1000m"
            limits:
              memory: "1024Mi"
              cpu: "2000m"
