apiVersion: apps/v1
kind: Deployment
metadata:
  name: stage-ubuntu
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
        - name: ubuntu-container
          image: ubuntu:latest
          ports:
            - containerPort: 80
          command: ["/bin/bash", "-c"]
          args:
            - |
              apt-get update \
              && DEBIAN_FRONTEND=noninteractive apt-get install -y apache2 \
              && cat > /var/www/html/index.html <<'EOF'
              <!DOCTYPE html>
              <html>
              <head><title>My Custom Page</title></head>
              <body>
                <h1>Hi my name is!</h1>
                <p>My name is!</p>
                <p>chika chik</p>
              </body>
              </html>
              EOF
              && apache2ctl -D FOREGROUND
