apiVersion: apps/v1
kind: Deployment
metadata:
  name: stage-ubuntu
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
        - name: ubuntu-container
          image: ubuntu:latest
          command: ["bash", "-c", "sleep infinity"]
          ports:
            - containerPort: 80
