apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-ubuntu
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dubovsky-andrey/kubernetes-public
    path: apps/github-runner-k8s-ubuntu/test
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
