apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-update-container
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Dubovsky-Andrey/kubernetes-public
    path: apps/github-runner/github-runner
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
