apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-config
  namespace: argocd-demo
data:
  init-apache.sh: |
    #!/bin/bash
    set -e
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get install -y apache2
    # Apache in foreground
    exec apache2ctl -D FOREGROUND
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stage-ubuntu
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
        - name: ubuntu-container
          image: ubuntu:latest
          # Start script from ConfigMap
          command: ["/bin/bash", "/opt/init-apache.sh"]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: apache-script
              mountPath: /opt/init-apache.sh
              subPath: init-apache.sh
      volumes:
        - name: apache-script
          configMap:
            name: apache-config
            defaultMode: 0755
