apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  project: default
  source:
    repoURL: https://github.com/Dubovsky-Andrey/kubernetes-public
    path: argocd-applications
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
