apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-test
  namespace: test
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  project: default
  source:
    repoURL: https://github.com/Dubovsky-Andrey/kubernetes-public
    path: test/argocd-apps
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
